# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  test:
    UUID: d319aec9-4d1f-49a2-b859-ce8854b3091a
    Url: http://localhost/
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
  #This is a generize fake client
  genderize:
    UUID: b68bfe16-1f2d-43e6-be37-9a85e1aeaf79
    Url: http://localhost/
    Icon: res:/webContent/icons/genderize.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
